-- Reference data derived from the public site (src/lib/data.ts).
-- GENERATED by scripts/generate-seed-sql.ts from the TypeScript seed modules.
-- Do not edit by hand; run `npm run db:seed:generate` instead.
-- LOCAL DEVELOPMENT ONLY. Loaded by `supabase db reset`; never pushed to a
-- hosted project (do not use `supabase db push --include-seed`).
-- Regions and countries come from the illustrative partner directory. The
-- country hub city/coordinates are the single globe pin for the country, not
-- a campus location. India (the home country) is included for activities.


insert into public.regions (slug, name, sort_order, data_source)
values ('europe', 'Europe', 0, 'directory');

insert into public.regions (slug, name, sort_order, data_source)
values ('middle-east', 'Middle East', 1, 'directory');

insert into public.regions (slug, name, sort_order, data_source)
values ('asia-pacific', 'Asia-Pacific', 2, 'directory');

insert into public.regions (slug, name, sort_order, data_source)
values ('north-america', 'North America', 3, 'directory');

insert into public.countries (slug, name, region_id, hub_city, hub_latitude, hub_longitude, summary, is_public, data_source)
values ('united-kingdom', 'United Kingdom', (select id from public.regions where slug = 'europe'), 'London', 51.5072, -0.1276, 'A frequent setting for semester and year-long study across engineering, management, and the arts.', true, 'directory');

insert into public.countries (slug, name, region_id, hub_city, hub_latitude, hub_longitude, summary, is_public, data_source)
values ('australia', 'Australia', (select id from public.regions where slug = 'asia-pacific'), 'Sydney', -33.8688, 151.2093, 'Research-led campuses on a southern academic calendar, often used for a full semester away.', true, 'directory');

insert into public.countries (slug, name, region_id, hub_city, hub_latitude, hub_longitude, summary, is_public, data_source)
values ('united-states', 'United States', (select id from public.regions where slug = 'north-america'), 'Boston', 42.3601, -71.0589, 'A wide field of universities, from research campuses to specialised schools, for exchange and visits.', true, 'directory');

insert into public.countries (slug, name, region_id, hub_city, hub_latitude, hub_longitude, summary, is_public, data_source)
values ('germany', 'Germany', (select id from public.regions where slug = 'europe'), 'Munich', 48.1351, 11.582, 'Technical universities and research partners, often aligned with engineering and the sciences.', true, 'directory');

insert into public.countries (slug, name, region_id, hub_city, hub_latitude, hub_longitude, summary, is_public, data_source)
values ('uae', 'United Arab Emirates', (select id from public.regions where slug = 'middle-east'), 'Dubai', 25.2048, 55.2708, 'A regional point for short academic visits and programmes that sit between Jaipur and further study.', true, 'directory');

insert into public.countries (slug, name, region_id, hub_city, hub_latitude, hub_longitude, summary, is_public, data_source)
values ('singapore', 'Singapore', (select id from public.regions where slug = 'asia-pacific'), 'Singapore', 1.3521, 103.8198, 'Compact, research-intensive campuses used here to stand in for Southeast Asian partnerships.', true, 'directory');

insert into public.countries (slug, name, region_id, hub_city, hub_latitude, hub_longitude, summary, is_public, data_source)
values ('france', 'France', (select id from public.regions where slug = 'europe'), 'Paris', 48.8566, 2.3522, 'A sample European capital for public affairs, design, and university visits.', true, 'directory');

insert into public.countries (slug, name, region_id, hub_city, hub_latitude, hub_longitude, summary, is_public, data_source)
values ('japan', 'Japan', (select id from public.regions where slug = 'asia-pacific'), 'Tokyo', 35.6762, 139.6503, 'A sample East Asian campus for exchange terms and faculty-led academic visits.', true, 'directory');

insert into public.countries (slug, name, region_id, hub_city, hub_latitude, hub_longitude, summary, is_public, data_source)
values ('canada', 'Canada', (select id from public.regions where slug = 'north-america'), 'Toronto', 43.6532, -79.3832, 'A sample North American research university for semester mobility.', true, 'directory');

insert into public.countries (slug, name, region_id, hub_city, hub_latitude, hub_longitude, summary, is_public, data_source)
values ('netherlands', 'Netherlands', (select id from public.regions where slug = 'europe'), 'Amsterdam', 52.3676, 4.9041, 'A sample continental European partner for taught programmes in English.', true, 'directory');

insert into public.countries (slug, name, region_id, hub_city, hub_latitude, hub_longitude, summary, is_public, data_source)
values ('south-korea', 'South Korea', (select id from public.regions where slug = 'asia-pacific'), 'Seoul', 37.5665, 126.978, 'A sample Korean campus on the illustrative network east of Jaipur.', true, 'directory');

insert into public.countries (slug, name, region_id, hub_city, hub_latitude, hub_longitude, summary, is_public, data_source)
values ('india', 'India', null, 'Jaipur', 26.9124, 75.7873, null, false, 'directory');

insert into public.programs (slug, program_type, name, description, general_audience, is_published, sort_order, data_source)
values ('student-exchange', 'student-exchange', 'Student Exchange', 'A term or an academic year at a partner university, with a place held for the return to MUJ.', null, true, 0, 'programme-catalogue');

insert into public.programs (slug, program_type, name, description, general_audience, is_published, sort_order, data_source)
values ('semester-exchange', 'semester-exchange', 'Semester Exchange', 'One semester abroad, aligned to the partner calendar, for students who want a single focused term.', null, true, 1, 'programme-catalogue');

insert into public.programs (slug, program_type, name, description, general_audience, is_published, sort_order, data_source)
values ('pathway-programs', 'pathway-programs', 'Pathway Programs', 'Structured routes that connect study at MUJ with a later stage at a partner institution.', null, true, 2, 'programme-catalogue');

insert into public.programs (slug, program_type, name, description, general_audience, is_published, sort_order, data_source)
values ('academic-visits', 'academic-visits', 'Academic Visits', 'Short faculty-led visits, summer schools, and delegations between Jaipur and campuses abroad.', null, true, 3, 'programme-catalogue');
