-- Names from the earlier illustrative directory, kept for DoIC review.
-- GENERATED by scripts/generate-seed-sql.ts. Do not edit by hand;
-- run `npm run db:seed:generate` instead.
-- None appears on the official MUJ partner page (reviewed 2026-09-30).
-- Never public (is_public = false), verification 'needs-review', no agreements.
-- Idempotent; requires 01_official.sql (countries) first.


insert into public.institutions (slug, name, normalized_name, country_id, city, latitude, longitude, location_verified, website, note, is_public, data_source, source_url, source_title, source_checked_on, verification)
values ('dir-university-of-birmingham', 'University of Birmingham', null, (select id from public.countries where slug = 'united-kingdom'), null, null, null, false, null, 'Shown in this platform''s earlier illustrative directory; not listed on the official MUJ partner page (reviewed 2026-09-30). Confirm with DoIC before publishing.', false, 'directory', null, null, '2026-09-30', 'needs-review')
on conflict (slug) do update set
  name = excluded.name,
  normalized_name = excluded.normalized_name,
  country_id = excluded.country_id,
  city = excluded.city,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  location_verified = excluded.location_verified,
  website = excluded.website,
  note = excluded.note,
  is_public = excluded.is_public,
  data_source = excluded.data_source,
  source_url = excluded.source_url,
  source_title = excluded.source_title,
  source_checked_on = excluded.source_checked_on,
  verification = excluded.verification;

insert into public.institutions (slug, name, normalized_name, country_id, city, latitude, longitude, location_verified, website, note, is_public, data_source, source_url, source_title, source_checked_on, verification)
values ('dir-lancaster-university', 'Lancaster University', null, (select id from public.countries where slug = 'united-kingdom'), null, null, null, false, null, 'Shown in this platform''s earlier illustrative directory; not listed on the official MUJ partner page (reviewed 2026-09-30). Confirm with DoIC before publishing.', false, 'directory', null, null, '2026-09-30', 'needs-review')
on conflict (slug) do update set
  name = excluded.name,
  normalized_name = excluded.normalized_name,
  country_id = excluded.country_id,
  city = excluded.city,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  location_verified = excluded.location_verified,
  website = excluded.website,
  note = excluded.note,
  is_public = excluded.is_public,
  data_source = excluded.data_source,
  source_url = excluded.source_url,
  source_title = excluded.source_title,
  source_checked_on = excluded.source_checked_on,
  verification = excluded.verification;

insert into public.institutions (slug, name, normalized_name, country_id, city, latitude, longitude, location_verified, website, note, is_public, data_source, source_url, source_title, source_checked_on, verification)
values ('dir-macquarie-university', 'Macquarie University', null, (select id from public.countries where slug = 'australia'), null, null, null, false, null, 'Shown in this platform''s earlier illustrative directory; not listed on the official MUJ partner page (reviewed 2026-09-30). Confirm with DoIC before publishing.', false, 'directory', null, null, '2026-09-30', 'needs-review')
on conflict (slug) do update set
  name = excluded.name,
  normalized_name = excluded.normalized_name,
  country_id = excluded.country_id,
  city = excluded.city,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  location_verified = excluded.location_verified,
  website = excluded.website,
  note = excluded.note,
  is_public = excluded.is_public,
  data_source = excluded.data_source,
  source_url = excluded.source_url,
  source_title = excluded.source_title,
  source_checked_on = excluded.source_checked_on,
  verification = excluded.verification;

insert into public.institutions (slug, name, normalized_name, country_id, city, latitude, longitude, location_verified, website, note, is_public, data_source, source_url, source_title, source_checked_on, verification)
values ('dir-boston-university', 'Boston University', null, (select id from public.countries where slug = 'united-states'), null, null, null, false, null, 'Shown in this platform''s earlier illustrative directory; not listed on the official MUJ partner page (reviewed 2026-09-30). Confirm with DoIC before publishing.', false, 'directory', null, null, '2026-09-30', 'needs-review')
on conflict (slug) do update set
  name = excluded.name,
  normalized_name = excluded.normalized_name,
  country_id = excluded.country_id,
  city = excluded.city,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  location_verified = excluded.location_verified,
  website = excluded.website,
  note = excluded.note,
  is_public = excluded.is_public,
  data_source = excluded.data_source,
  source_url = excluded.source_url,
  source_title = excluded.source_title,
  source_checked_on = excluded.source_checked_on,
  verification = excluded.verification;

insert into public.institutions (slug, name, normalized_name, country_id, city, latitude, longitude, location_verified, website, note, is_public, data_source, source_url, source_title, source_checked_on, verification)
values ('dir-university-of-massachusetts', 'University of Massachusetts', null, (select id from public.countries where slug = 'united-states'), null, null, null, false, null, 'Shown in this platform''s earlier illustrative directory; not listed on the official MUJ partner page (reviewed 2026-09-30). Confirm with DoIC before publishing.', false, 'directory', null, null, '2026-09-30', 'needs-review')
on conflict (slug) do update set
  name = excluded.name,
  normalized_name = excluded.normalized_name,
  country_id = excluded.country_id,
  city = excluded.city,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  location_verified = excluded.location_verified,
  website = excluded.website,
  note = excluded.note,
  is_public = excluded.is_public,
  data_source = excluded.data_source,
  source_url = excluded.source_url,
  source_title = excluded.source_title,
  source_checked_on = excluded.source_checked_on,
  verification = excluded.verification;

insert into public.institutions (slug, name, normalized_name, country_id, city, latitude, longitude, location_verified, website, note, is_public, data_source, source_url, source_title, source_checked_on, verification)
values ('dir-technical-university-of-munich', 'Technical University of Munich', null, (select id from public.countries where slug = 'germany'), null, null, null, false, null, 'Shown in this platform''s earlier illustrative directory; not listed on the official MUJ partner page (reviewed 2026-09-30). Confirm with DoIC before publishing.', false, 'directory', null, null, '2026-09-30', 'needs-review')
on conflict (slug) do update set
  name = excluded.name,
  normalized_name = excluded.normalized_name,
  country_id = excluded.country_id,
  city = excluded.city,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  location_verified = excluded.location_verified,
  website = excluded.website,
  note = excluded.note,
  is_public = excluded.is_public,
  data_source = excluded.data_source,
  source_url = excluded.source_url,
  source_title = excluded.source_title,
  source_checked_on = excluded.source_checked_on,
  verification = excluded.verification;

insert into public.institutions (slug, name, normalized_name, country_id, city, latitude, longitude, location_verified, website, note, is_public, data_source, source_url, source_title, source_checked_on, verification)
values ('dir-lmu-munich', 'LMU Munich', null, (select id from public.countries where slug = 'germany'), null, null, null, false, null, 'Shown in this platform''s earlier illustrative directory; not listed on the official MUJ partner page (reviewed 2026-09-30). Confirm with DoIC before publishing.', false, 'directory', null, null, '2026-09-30', 'needs-review')
on conflict (slug) do update set
  name = excluded.name,
  normalized_name = excluded.normalized_name,
  country_id = excluded.country_id,
  city = excluded.city,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  location_verified = excluded.location_verified,
  website = excluded.website,
  note = excluded.note,
  is_public = excluded.is_public,
  data_source = excluded.data_source,
  source_url = excluded.source_url,
  source_title = excluded.source_title,
  source_checked_on = excluded.source_checked_on,
  verification = excluded.verification;

insert into public.institutions (slug, name, normalized_name, country_id, city, latitude, longitude, location_verified, website, note, is_public, data_source, source_url, source_title, source_checked_on, verification)
values ('dir-university-of-wollongong-in-dubai', 'University of Wollongong in Dubai', null, (select id from public.countries where slug = 'united-arab-emirates'), null, null, null, false, null, 'Shown in this platform''s earlier illustrative directory; not listed on the official MUJ partner page (reviewed 2026-09-30). Confirm with DoIC before publishing.', false, 'directory', null, null, '2026-09-30', 'needs-review')
on conflict (slug) do update set
  name = excluded.name,
  normalized_name = excluded.normalized_name,
  country_id = excluded.country_id,
  city = excluded.city,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  location_verified = excluded.location_verified,
  website = excluded.website,
  note = excluded.note,
  is_public = excluded.is_public,
  data_source = excluded.data_source,
  source_url = excluded.source_url,
  source_title = excluded.source_title,
  source_checked_on = excluded.source_checked_on,
  verification = excluded.verification;

insert into public.institutions (slug, name, normalized_name, country_id, city, latitude, longitude, location_verified, website, note, is_public, data_source, source_url, source_title, source_checked_on, verification)
values ('dir-middlesex-university-dubai', 'Middlesex University Dubai', null, (select id from public.countries where slug = 'united-arab-emirates'), null, null, null, false, null, 'Shown in this platform''s earlier illustrative directory; not listed on the official MUJ partner page (reviewed 2026-09-30). Confirm with DoIC before publishing.', false, 'directory', null, null, '2026-09-30', 'needs-review')
on conflict (slug) do update set
  name = excluded.name,
  normalized_name = excluded.normalized_name,
  country_id = excluded.country_id,
  city = excluded.city,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  location_verified = excluded.location_verified,
  website = excluded.website,
  note = excluded.note,
  is_public = excluded.is_public,
  data_source = excluded.data_source,
  source_url = excluded.source_url,
  source_title = excluded.source_title,
  source_checked_on = excluded.source_checked_on,
  verification = excluded.verification;

insert into public.institutions (slug, name, normalized_name, country_id, city, latitude, longitude, location_verified, website, note, is_public, data_source, source_url, source_title, source_checked_on, verification)
values ('dir-national-university-of-singapore', 'National University of Singapore', null, (select id from public.countries where slug = 'singapore'), null, null, null, false, null, 'Shown in this platform''s earlier illustrative directory; not listed on the official MUJ partner page (reviewed 2026-09-30). Confirm with DoIC before publishing.', false, 'directory', null, null, '2026-09-30', 'needs-review')
on conflict (slug) do update set
  name = excluded.name,
  normalized_name = excluded.normalized_name,
  country_id = excluded.country_id,
  city = excluded.city,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  location_verified = excluded.location_verified,
  website = excluded.website,
  note = excluded.note,
  is_public = excluded.is_public,
  data_source = excluded.data_source,
  source_url = excluded.source_url,
  source_title = excluded.source_title,
  source_checked_on = excluded.source_checked_on,
  verification = excluded.verification;

insert into public.institutions (slug, name, normalized_name, country_id, city, latitude, longitude, location_verified, website, note, is_public, data_source, source_url, source_title, source_checked_on, verification)
values ('dir-singapore-management-university', 'Singapore Management University', null, (select id from public.countries where slug = 'singapore'), null, null, null, false, null, 'Shown in this platform''s earlier illustrative directory; not listed on the official MUJ partner page (reviewed 2026-09-30). Confirm with DoIC before publishing.', false, 'directory', null, null, '2026-09-30', 'needs-review')
on conflict (slug) do update set
  name = excluded.name,
  normalized_name = excluded.normalized_name,
  country_id = excluded.country_id,
  city = excluded.city,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  location_verified = excluded.location_verified,
  website = excluded.website,
  note = excluded.note,
  is_public = excluded.is_public,
  data_source = excluded.data_source,
  source_url = excluded.source_url,
  source_title = excluded.source_title,
  source_checked_on = excluded.source_checked_on,
  verification = excluded.verification;

insert into public.institutions (slug, name, normalized_name, country_id, city, latitude, longitude, location_verified, website, note, is_public, data_source, source_url, source_title, source_checked_on, verification)
values ('dir-sciences-po', 'Sciences Po', null, (select id from public.countries where slug = 'france'), null, null, null, false, null, 'Shown in this platform''s earlier illustrative directory; not listed on the official MUJ partner page (reviewed 2026-09-30). Confirm with DoIC before publishing.', false, 'directory', null, null, '2026-09-30', 'needs-review')
on conflict (slug) do update set
  name = excluded.name,
  normalized_name = excluded.normalized_name,
  country_id = excluded.country_id,
  city = excluded.city,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  location_verified = excluded.location_verified,
  website = excluded.website,
  note = excluded.note,
  is_public = excluded.is_public,
  data_source = excluded.data_source,
  source_url = excluded.source_url,
  source_title = excluded.source_title,
  source_checked_on = excluded.source_checked_on,
  verification = excluded.verification;

insert into public.institutions (slug, name, normalized_name, country_id, city, latitude, longitude, location_verified, website, note, is_public, data_source, source_url, source_title, source_checked_on, verification)
values ('dir-waseda-university', 'Waseda University', null, (select id from public.countries where slug = 'japan'), null, null, null, false, null, 'Shown in this platform''s earlier illustrative directory; not listed on the official MUJ partner page (reviewed 2026-09-30). Confirm with DoIC before publishing.', false, 'directory', null, null, '2026-09-30', 'needs-review')
on conflict (slug) do update set
  name = excluded.name,
  normalized_name = excluded.normalized_name,
  country_id = excluded.country_id,
  city = excluded.city,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  location_verified = excluded.location_verified,
  website = excluded.website,
  note = excluded.note,
  is_public = excluded.is_public,
  data_source = excluded.data_source,
  source_url = excluded.source_url,
  source_title = excluded.source_title,
  source_checked_on = excluded.source_checked_on,
  verification = excluded.verification;

insert into public.institutions (slug, name, normalized_name, country_id, city, latitude, longitude, location_verified, website, note, is_public, data_source, source_url, source_title, source_checked_on, verification)
values ('dir-university-of-toronto', 'University of Toronto', null, (select id from public.countries where slug = 'canada'), null, null, null, false, null, 'Shown in this platform''s earlier illustrative directory; not listed on the official MUJ partner page (reviewed 2026-09-30). Confirm with DoIC before publishing.', false, 'directory', null, null, '2026-09-30', 'needs-review')
on conflict (slug) do update set
  name = excluded.name,
  normalized_name = excluded.normalized_name,
  country_id = excluded.country_id,
  city = excluded.city,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  location_verified = excluded.location_verified,
  website = excluded.website,
  note = excluded.note,
  is_public = excluded.is_public,
  data_source = excluded.data_source,
  source_url = excluded.source_url,
  source_title = excluded.source_title,
  source_checked_on = excluded.source_checked_on,
  verification = excluded.verification;

insert into public.institutions (slug, name, normalized_name, country_id, city, latitude, longitude, location_verified, website, note, is_public, data_source, source_url, source_title, source_checked_on, verification)
values ('dir-university-of-amsterdam', 'University of Amsterdam', null, (select id from public.countries where slug = 'netherlands'), null, null, null, false, null, 'Shown in this platform''s earlier illustrative directory; not listed on the official MUJ partner page (reviewed 2026-09-30). Confirm with DoIC before publishing.', false, 'directory', null, null, '2026-09-30', 'needs-review')
on conflict (slug) do update set
  name = excluded.name,
  normalized_name = excluded.normalized_name,
  country_id = excluded.country_id,
  city = excluded.city,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  location_verified = excluded.location_verified,
  website = excluded.website,
  note = excluded.note,
  is_public = excluded.is_public,
  data_source = excluded.data_source,
  source_url = excluded.source_url,
  source_title = excluded.source_title,
  source_checked_on = excluded.source_checked_on,
  verification = excluded.verification;

insert into public.institutions (slug, name, normalized_name, country_id, city, latitude, longitude, location_verified, website, note, is_public, data_source, source_url, source_title, source_checked_on, verification)
values ('dir-yonsei-university', 'Yonsei University', null, (select id from public.countries where slug = 'south-korea'), null, null, null, false, null, 'Shown in this platform''s earlier illustrative directory; not listed on the official MUJ partner page (reviewed 2026-09-30). Confirm with DoIC before publishing.', false, 'directory', null, null, '2026-09-30', 'needs-review')
on conflict (slug) do update set
  name = excluded.name,
  normalized_name = excluded.normalized_name,
  country_id = excluded.country_id,
  city = excluded.city,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  location_verified = excluded.location_verified,
  website = excluded.website,
  note = excluded.note,
  is_public = excluded.is_public,
  data_source = excluded.data_source,
  source_url = excluded.source_url,
  source_title = excluded.source_title,
  source_checked_on = excluded.source_checked_on,
  verification = excluded.verification;
