-- Institutions from the public illustrative directory (src/lib/directory.ts).
-- GENERATED by scripts/generate-seed-sql.ts from the TypeScript seed modules.
-- Do not edit by hand; run `npm run db:seed:generate` instead.
-- LOCAL DEVELOPMENT ONLY. Loaded by `supabase db reset`; never pushed to a
-- hosted project (do not use `supabase db push --include-seed`).
-- Names are sample institutions, not confirmed partners. City and coordinates
-- are left NULL: the directory only carries the country hub city, which is
-- not the campus city. The country-level note lives on public.countries.


insert into public.institutions (slug, name, country_id, city, latitude, longitude, location_verified, is_public, data_source)
values ('dir-sciences-po', 'Sciences Po', (select id from public.countries where slug = 'france'), null, null, null, false, true, 'directory');

insert into public.institutions (slug, name, country_id, city, latitude, longitude, location_verified, is_public, data_source)
values ('dir-lmu-munich', 'LMU Munich', (select id from public.countries where slug = 'germany'), null, null, null, false, true, 'directory');

insert into public.institutions (slug, name, country_id, city, latitude, longitude, location_verified, is_public, data_source)
values ('dir-technical-university-of-munich', 'Technical University of Munich', (select id from public.countries where slug = 'germany'), null, null, null, false, true, 'directory');

insert into public.institutions (slug, name, country_id, city, latitude, longitude, location_verified, is_public, data_source)
values ('dir-university-of-amsterdam', 'University of Amsterdam', (select id from public.countries where slug = 'netherlands'), null, null, null, false, true, 'directory');

insert into public.institutions (slug, name, country_id, city, latitude, longitude, location_verified, is_public, data_source)
values ('dir-lancaster-university', 'Lancaster University', (select id from public.countries where slug = 'united-kingdom'), null, null, null, false, true, 'directory');

insert into public.institutions (slug, name, country_id, city, latitude, longitude, location_verified, is_public, data_source)
values ('dir-university-of-birmingham', 'University of Birmingham', (select id from public.countries where slug = 'united-kingdom'), null, null, null, false, true, 'directory');

insert into public.institutions (slug, name, country_id, city, latitude, longitude, location_verified, is_public, data_source)
values ('dir-middlesex-university-dubai', 'Middlesex University Dubai', (select id from public.countries where slug = 'uae'), null, null, null, false, true, 'directory');

insert into public.institutions (slug, name, country_id, city, latitude, longitude, location_verified, is_public, data_source)
values ('dir-university-of-wollongong-in-dubai', 'University of Wollongong in Dubai', (select id from public.countries where slug = 'uae'), null, null, null, false, true, 'directory');

insert into public.institutions (slug, name, country_id, city, latitude, longitude, location_verified, is_public, data_source)
values ('dir-macquarie-university', 'Macquarie University', (select id from public.countries where slug = 'australia'), null, null, null, false, true, 'directory');

insert into public.institutions (slug, name, country_id, city, latitude, longitude, location_verified, is_public, data_source)
values ('dir-university-of-newcastle', 'University of Newcastle', (select id from public.countries where slug = 'australia'), null, null, null, false, true, 'directory');

insert into public.institutions (slug, name, country_id, city, latitude, longitude, location_verified, is_public, data_source)
values ('dir-waseda-university', 'Waseda University', (select id from public.countries where slug = 'japan'), null, null, null, false, true, 'directory');

insert into public.institutions (slug, name, country_id, city, latitude, longitude, location_verified, is_public, data_source)
values ('dir-national-university-of-singapore', 'National University of Singapore', (select id from public.countries where slug = 'singapore'), null, null, null, false, true, 'directory');

insert into public.institutions (slug, name, country_id, city, latitude, longitude, location_verified, is_public, data_source)
values ('dir-singapore-management-university', 'Singapore Management University', (select id from public.countries where slug = 'singapore'), null, null, null, false, true, 'directory');

insert into public.institutions (slug, name, country_id, city, latitude, longitude, location_verified, is_public, data_source)
values ('dir-yonsei-university', 'Yonsei University', (select id from public.countries where slug = 'south-korea'), null, null, null, false, true, 'directory');

insert into public.institutions (slug, name, country_id, city, latitude, longitude, location_verified, is_public, data_source)
values ('dir-university-of-toronto', 'University of Toronto', (select id from public.countries where slug = 'canada'), null, null, null, false, true, 'directory');

insert into public.institutions (slug, name, country_id, city, latitude, longitude, location_verified, is_public, data_source)
values ('dir-boston-university', 'Boston University', (select id from public.countries where slug = 'united-states'), null, null, null, false, true, 'directory');

insert into public.institutions (slug, name, country_id, city, latitude, longitude, location_verified, is_public, data_source)
values ('dir-university-of-massachusetts', 'University of Massachusetts', (select id from public.countries where slug = 'united-states'), null, null, null, false, true, 'directory');
