-- FICTIONAL SAMPLE DATA for the internal portal workflow.
-- GENERATED by scripts/generate-seed-sql.ts from the TypeScript seed modules.
-- Do not edit by hand; run `npm run db:seed:generate` instead.
-- LOCAL DEVELOPMENT ONLY. Loaded by `supabase db reset`; never pushed to a
-- hosted project (do not use `supabase db push --include-seed`).
-- Every row is marked data_source = 'sample'. None of these is a DoIC record,
-- an agreement of Manipal University Jaipur, or a published deadline.
-- Sample rows are never public (is_public / is_published = false).


insert into public.institutions (slug, name, country_id, city, latitude, longitude, website, note, is_public, data_source)
values ('smp-harbour', 'Example Harbour University', (select id from public.countries where slug = 'united-kingdom'), null, null, null, null, null, false, 'sample');

insert into public.institutions (slug, name, country_id, city, latitude, longitude, website, note, is_public, data_source)
values ('smp-alpine', 'Example Alpine Institute of Technology', (select id from public.countries where slug = 'germany'), null, null, null, null, null, false, 'sample');

insert into public.institutions (slug, name, country_id, city, latitude, longitude, website, note, is_public, data_source)
values ('smp-coastal', 'Example Coastal University', (select id from public.countries where slug = 'australia'), null, null, null, null, null, false, 'sample');

insert into public.institutions (slug, name, country_id, city, latitude, longitude, website, note, is_public, data_source)
values ('smp-lakes', 'Example Lakes University', (select id from public.countries where slug = 'canada'), null, null, null, null, null, false, 'sample');

insert into public.institutions (slug, name, country_id, city, latitude, longitude, website, note, is_public, data_source)
values ('smp-gulf', 'Example Gulf Institute', (select id from public.countries where slug = 'uae'), null, null, null, null, null, false, 'sample');

insert into public.institutions (slug, name, country_id, city, latitude, longitude, website, note, is_public, data_source)
values ('smp-straits', 'Example Straits University', (select id from public.countries where slug = 'singapore'), null, null, null, null, null, false, 'sample');

insert into public.collaboration_areas (slug, name, data_source)
values ('engineering', 'Engineering', 'sample');

insert into public.collaboration_areas (slug, name, data_source)
values ('management', 'Management', 'sample');

insert into public.collaboration_areas (slug, name, data_source)
values ('faculty-exchange', 'Faculty exchange', 'sample');

insert into public.collaboration_areas (slug, name, data_source)
values ('student-mobility', 'Student mobility', 'sample');

insert into public.collaboration_areas (slug, name, data_source)
values ('credit-transfer', 'Credit transfer', 'sample');

insert into public.collaboration_areas (slug, name, data_source)
values ('applied-sciences', 'Applied sciences', 'sample');

insert into public.collaboration_areas (slug, name, data_source)
values ('joint-research', 'Joint research', 'sample');

insert into public.collaboration_areas (slug, name, data_source)
values ('doctoral-visits', 'Doctoral visits', 'sample');

insert into public.collaboration_areas (slug, name, data_source)
values ('summer-schools', 'Summer schools', 'sample');

insert into public.collaboration_areas (slug, name, data_source)
values ('computer-science', 'Computer science', 'sample');

insert into public.collaboration_areas (slug, name, data_source)
values ('pathway-study', 'Pathway study', 'sample');

insert into public.collaboration_areas (slug, name, data_source)
values ('academic-visits', 'Academic visits', 'sample');

insert into public.collaboration_areas (slug, name, data_source)
values ('short-programmes', 'Short programmes', 'sample');

insert into public.collaboration_areas (slug, name, data_source)
values ('business', 'Business', 'sample');

insert into public.collaboration_areas (slug, name, data_source)
values ('design', 'Design', 'sample');

insert into public.collaboration_areas (slug, name, data_source)
values ('data-science', 'Data science', 'sample');

insert into public.agreements (code, reference, institution_id, title, agreement_type, record_status, start_date, end_date, renewal, notes, data_source)
values ('agr-001', 'SAMPLE-AGR-001', (select id from public.institutions where slug = 'smp-harbour'), 'Framework memorandum (sample)', 'mou', 'signed', '2021-12-01', '2026-11-30', 'by-review', 'Sample record. Renewal review would be scheduled before the end date.', 'sample');

insert into public.agreement_collaboration_areas (agreement_id, collaboration_area_id, position)
values ((select id from public.agreements where code = 'agr-001'), (select id from public.collaboration_areas where slug = 'engineering'), 0);

insert into public.agreement_collaboration_areas (agreement_id, collaboration_area_id, position)
values ((select id from public.agreements where code = 'agr-001'), (select id from public.collaboration_areas where slug = 'management'), 1);

insert into public.agreement_collaboration_areas (agreement_id, collaboration_area_id, position)
values ((select id from public.agreements where code = 'agr-001'), (select id from public.collaboration_areas where slug = 'faculty-exchange'), 2);

insert into public.agreements (code, reference, institution_id, title, agreement_type, record_status, start_date, end_date, renewal, notes, data_source)
values ('agr-002', 'SAMPLE-AGR-002', (select id from public.institutions where slug = 'smp-harbour'), 'Student exchange agreement (sample)', 'student-exchange', 'signed', '2023-07-01', '2028-06-30', 'by-review', null, 'sample');

insert into public.agreement_collaboration_areas (agreement_id, collaboration_area_id, position)
values ((select id from public.agreements where code = 'agr-002'), (select id from public.collaboration_areas where slug = 'student-mobility'), 0);

insert into public.agreement_collaboration_areas (agreement_id, collaboration_area_id, position)
values ((select id from public.agreements where code = 'agr-002'), (select id from public.collaboration_areas where slug = 'credit-transfer'), 1);

insert into public.agreements (code, reference, institution_id, title, agreement_type, record_status, start_date, end_date, renewal, notes, data_source)
values ('agr-003', 'SAMPLE-AGR-003', (select id from public.institutions where slug = 'smp-alpine'), 'Research collaboration agreement (sample)', 'research-collaboration', 'signed', '2024-03-01', '2029-02-28', 'by-review', null, 'sample');

insert into public.agreement_collaboration_areas (agreement_id, collaboration_area_id, position)
values ((select id from public.agreements where code = 'agr-003'), (select id from public.collaboration_areas where slug = 'applied-sciences'), 0);

insert into public.agreement_collaboration_areas (agreement_id, collaboration_area_id, position)
values ((select id from public.agreements where code = 'agr-003'), (select id from public.collaboration_areas where slug = 'joint-research'), 1);

insert into public.agreement_collaboration_areas (agreement_id, collaboration_area_id, position)
values ((select id from public.agreements where code = 'agr-003'), (select id from public.collaboration_areas where slug = 'doctoral-visits'), 2);

insert into public.agreements (code, reference, institution_id, title, agreement_type, record_status, start_date, end_date, renewal, notes, data_source)
values ('agr-004', 'SAMPLE-AGR-004', (select id from public.institutions where slug = 'smp-alpine'), 'Earlier framework memorandum (sample)', 'mou', 'signed', '2019-06-01', '2024-05-31', null, 'Sample record kept for history; superseded by SAMPLE-AGR-003.', 'sample');

insert into public.agreement_collaboration_areas (agreement_id, collaboration_area_id, position)
values ((select id from public.agreements where code = 'agr-004'), (select id from public.collaboration_areas where slug = 'engineering'), 0);

insert into public.agreements (code, reference, institution_id, title, agreement_type, record_status, start_date, end_date, renewal, notes, data_source)
values ('agr-005', 'SAMPLE-AGR-005', (select id from public.institutions where slug = 'smp-coastal'), 'Semester exchange agreement (sample)', 'student-exchange', 'signed', '2020-08-01', '2025-07-31', 'by-review', null, 'sample');

insert into public.agreement_collaboration_areas (agreement_id, collaboration_area_id, position)
values ((select id from public.agreements where code = 'agr-005'), (select id from public.collaboration_areas where slug = 'student-mobility'), 0);

insert into public.agreements (code, reference, institution_id, title, agreement_type, record_status, start_date, end_date, renewal, notes, data_source)
values ('agr-006', 'SAMPLE-AGR-006', (select id from public.institutions where slug = 'smp-coastal'), 'Renewed exchange agreement — draft (sample)', 'student-exchange', 'draft', null, null, null, 'Sample draft. Dates are left empty until signature.', 'sample');

insert into public.agreement_collaboration_areas (agreement_id, collaboration_area_id, position)
values ((select id from public.agreements where code = 'agr-006'), (select id from public.collaboration_areas where slug = 'student-mobility'), 0);

insert into public.agreement_collaboration_areas (agreement_id, collaboration_area_id, position)
values ((select id from public.agreements where code = 'agr-006'), (select id from public.collaboration_areas where slug = 'summer-schools'), 1);

insert into public.agreements (code, reference, institution_id, title, agreement_type, record_status, start_date, end_date, renewal, notes, data_source)
values ('agr-007', 'SAMPLE-AGR-007', (select id from public.institutions where slug = 'smp-lakes'), 'Dual degree proposal (sample)', 'dual-degree', 'under-review', null, null, null, null, 'sample');

insert into public.agreement_collaboration_areas (agreement_id, collaboration_area_id, position)
values ((select id from public.agreements where code = 'agr-007'), (select id from public.collaboration_areas where slug = 'computer-science'), 0);

insert into public.agreement_collaboration_areas (agreement_id, collaboration_area_id, position)
values ((select id from public.agreements where code = 'agr-007'), (select id from public.collaboration_areas where slug = 'pathway-study'), 1);

insert into public.agreements (code, reference, institution_id, title, agreement_type, record_status, start_date, end_date, renewal, notes, data_source)
values ('agr-008', 'SAMPLE-AGR-008', (select id from public.institutions where slug = 'smp-gulf'), 'Framework memorandum (sample)', 'mou', 'signed', '2026-11-01', '2031-10-31', 'by-review', null, 'sample');

insert into public.agreement_collaboration_areas (agreement_id, collaboration_area_id, position)
values ((select id from public.agreements where code = 'agr-008'), (select id from public.collaboration_areas where slug = 'academic-visits'), 0);

insert into public.agreement_collaboration_areas (agreement_id, collaboration_area_id, position)
values ((select id from public.agreements where code = 'agr-008'), (select id from public.collaboration_areas where slug = 'short-programmes'), 1);

insert into public.agreements (code, reference, institution_id, title, agreement_type, record_status, start_date, end_date, renewal, notes, data_source)
values ('agr-009', 'SAMPLE-AGR-009', (select id from public.institutions where slug = 'smp-straits'), 'Framework memorandum (sample)', 'mou', 'signed', '2022-04-01', '2026-10-20', 'automatic', null, 'sample');

insert into public.agreement_collaboration_areas (agreement_id, collaboration_area_id, position)
values ((select id from public.agreements where code = 'agr-009'), (select id from public.collaboration_areas where slug = 'business'), 0);

insert into public.agreement_collaboration_areas (agreement_id, collaboration_area_id, position)
values ((select id from public.agreements where code = 'agr-009'), (select id from public.collaboration_areas where slug = 'design'), 1);

insert into public.agreement_collaboration_areas (agreement_id, collaboration_area_id, position)
values ((select id from public.agreements where code = 'agr-009'), (select id from public.collaboration_areas where slug = 'student-mobility'), 2);

insert into public.agreements (code, reference, institution_id, title, agreement_type, record_status, start_date, end_date, renewal, notes, data_source)
values ('agr-010', 'SAMPLE-AGR-010', (select id from public.institutions where slug = 'smp-straits'), 'Joint research memorandum (sample)', 'research-collaboration', 'terminated', '2021-01-10', '2026-01-09', null, 'Sample record ended early by mutual agreement.', 'sample');

insert into public.agreement_collaboration_areas (agreement_id, collaboration_area_id, position)
values ((select id from public.agreements where code = 'agr-010'), (select id from public.collaboration_areas where slug = 'data-science'), 0);

insert into public.program_availability (code, program_id, institution_id, agreement_id, availability, duration, intake, application_start, application_end, eligibility, credit_information, notes, is_published, data_source)
values ('off-001', (select id from public.programs where slug = 'semester-exchange'), (select id from public.institutions where slug = 'smp-harbour'), (select id from public.agreements where code = 'agr-002'), 'open', 'One semester', 'Spring term', '2026-09-01', '2026-10-31', null, null, null, false, 'sample');

insert into public.program_availability (code, program_id, institution_id, agreement_id, availability, duration, intake, application_start, application_end, eligibility, credit_information, notes, is_published, data_source)
values ('off-002', (select id from public.programs where slug = 'student-exchange'), (select id from public.institutions where slug = 'smp-harbour'), (select id from public.agreements where code = 'agr-002'), 'open', 'One academic year', 'Autumn term', '2026-11-01', '2027-01-31', null, null, null, false, 'sample');

insert into public.program_availability (code, program_id, institution_id, agreement_id, availability, duration, intake, application_start, application_end, eligibility, credit_information, notes, is_published, data_source)
values ('off-003', (select id from public.programs where slug = 'academic-visits'), (select id from public.institutions where slug = 'smp-alpine'), (select id from public.agreements where code = 'agr-003'), 'open', 'Two weeks', 'Summer', '2026-09-15', '2026-10-08', null, null, 'Sample faculty-led visit format.', false, 'sample');

insert into public.program_availability (code, program_id, institution_id, agreement_id, availability, duration, intake, application_start, application_end, eligibility, credit_information, notes, is_published, data_source)
values ('off-004', (select id from public.programs where slug = 'semester-exchange'), (select id from public.institutions where slug = 'smp-coastal'), (select id from public.agreements where code = 'agr-005'), 'suspended', 'One semester', 'Southern-hemisphere semester', null, null, null, null, 'Suspended in this sample until the renewal draft is signed.', false, 'sample');

insert into public.program_availability (code, program_id, institution_id, agreement_id, availability, duration, intake, application_start, application_end, eligibility, credit_information, notes, is_published, data_source)
values ('off-005', (select id from public.programs where slug = 'pathway-programs'), (select id from public.institutions where slug = 'smp-lakes'), null, null, 'Two years at MUJ + two years at partner', null, null, null, null, null, 'Availability is not recorded while the sample dual degree proposal is under review.', false, 'sample');

insert into public.program_availability (code, program_id, institution_id, agreement_id, availability, duration, intake, application_start, application_end, eligibility, credit_information, notes, is_published, data_source)
values ('off-006', (select id from public.programs where slug = 'academic-visits'), (select id from public.institutions where slug = 'smp-gulf'), (select id from public.agreements where code = 'agr-008'), 'closed', 'One week', 'Winter', null, null, null, null, 'Opens after the sample agreement start date.', false, 'sample');

insert into public.program_availability (code, program_id, institution_id, agreement_id, availability, duration, intake, application_start, application_end, eligibility, credit_information, notes, is_published, data_source)
values ('off-007', (select id from public.programs where slug = 'semester-exchange'), (select id from public.institutions where slug = 'smp-straits'), (select id from public.agreements where code = 'agr-009'), 'open', 'One semester', 'Spring term', '2026-08-15', '2026-10-10', null, null, null, false, 'sample');

insert into public.program_availability (code, program_id, institution_id, agreement_id, availability, duration, intake, application_start, application_end, eligibility, credit_information, notes, is_published, data_source)
values ('off-008', (select id from public.programs where slug = 'student-exchange'), (select id from public.institutions where slug = 'smp-alpine'), (select id from public.agreements where code = 'agr-003'), 'closed', 'One academic year', 'Winter semester', '2026-01-10', '2026-03-15', null, null, null, false, 'sample');

insert into public.opportunities (code, title, program_id, availability_id, institution_id, opens_on, deadline, record_status, summary, data_source)
values ('opp-001', 'Spring semester exchange call (sample)', (select id from public.programs where slug = 'semester-exchange'), (select id from public.program_availability where code = 'off-001'), (select id from public.institutions where slug = 'smp-harbour'), '2026-09-01', '2026-10-31', 'published', 'Sample call for a one-semester exchange place at a fictional partner.', 'sample');

insert into public.opportunities (code, title, program_id, availability_id, institution_id, opens_on, deadline, record_status, summary, data_source)
values ('opp-002', 'Faculty-led summer visit (sample)', (select id from public.programs where slug = 'academic-visits'), (select id from public.program_availability where code = 'off-003'), (select id from public.institutions where slug = 'smp-alpine'), '2026-09-15', '2026-10-08', 'published', 'Sample two-week academic visit call.', 'sample');

insert into public.opportunities (code, title, program_id, availability_id, institution_id, opens_on, deadline, record_status, summary, data_source)
values ('opp-003', 'Spring semester exchange call (sample)', (select id from public.programs where slug = 'semester-exchange'), (select id from public.program_availability where code = 'off-007'), (select id from public.institutions where slug = 'smp-straits'), '2026-08-15', '2026-10-10', 'published', 'Sample call for a one-semester exchange place at a fictional partner.', 'sample');

insert into public.opportunities (code, title, program_id, availability_id, institution_id, opens_on, deadline, record_status, summary, data_source)
values ('opp-004', 'Full-year exchange call (sample)', (select id from public.programs where slug = 'student-exchange'), (select id from public.program_availability where code = 'off-002'), (select id from public.institutions where slug = 'smp-harbour'), '2026-11-01', '2027-01-31', 'published', 'Sample call for a full academic year abroad.', 'sample');

insert into public.opportunities (code, title, program_id, availability_id, institution_id, opens_on, deadline, record_status, summary, data_source)
values ('opp-005', 'Winter semester year exchange (sample)', (select id from public.programs where slug = 'student-exchange'), (select id from public.program_availability where code = 'off-008'), (select id from public.institutions where slug = 'smp-alpine'), '2026-01-10', '2026-03-15', 'published', 'Sample call that has already closed.', 'sample');

insert into public.opportunities (code, title, program_id, availability_id, institution_id, opens_on, deadline, record_status, summary, data_source)
values ('opp-006', 'Pathway programme information call (sample)', (select id from public.programs where slug = 'pathway-programs'), (select id from public.program_availability where code = 'off-005'), (select id from public.institutions where slug = 'smp-lakes'), null, null, 'draft', 'Sample draft kept unpublished while the related proposal is reviewed.', 'sample');

insert into public.opportunities (code, title, program_id, availability_id, institution_id, opens_on, deadline, record_status, summary, data_source)
values ('opp-007', 'Southern semester exchange (sample)', (select id from public.programs where slug = 'semester-exchange'), (select id from public.program_availability where code = 'off-004'), (select id from public.institutions where slug = 'smp-coastal'), '2025-02-01', '2025-03-31', 'archived', 'Sample archived call from a previous cycle.', 'sample');

insert into public.opportunities (code, title, program_id, availability_id, institution_id, opens_on, deadline, record_status, summary, data_source)
values ('opp-008', 'Academic visits interest register (sample)', (select id from public.programs where slug = 'academic-visits'), null, null, '2026-09-20', '2026-12-15', 'published', 'Sample open register not tied to a single institution.', 'sample');

insert into public.documents (code, title, document_type, status, revised_on, description, data_source)
values ('doc-001', 'Framework memorandum — signed copy (sample)', 'agreement', 'final', '2021-12-01', 'Placeholder for the signed copy of SAMPLE-AGR-001.', 'sample');

insert into public.documents (code, title, document_type, status, revised_on, description, data_source)
values ('doc-002', 'Framework memorandum — renewal draft (sample)', 'agreement', 'draft', '2026-09-12', 'Placeholder for a renewal draft ahead of the SAMPLE-AGR-001 end date.', 'sample');

insert into public.documents (code, title, document_type, status, revised_on, description, data_source)
values ('doc-003', 'Research collaboration agreement (sample)', 'agreement', 'final', '2024-03-01', null, 'sample');

insert into public.documents (code, title, document_type, status, revised_on, description, data_source)
values ('doc-004', 'Renewed exchange agreement — working draft (sample)', 'agreement', 'under-review', '2026-08-28', null, 'sample');

insert into public.documents (code, title, document_type, status, revised_on, description, data_source)
values ('doc-005', 'Semester exchange student guide (sample)', 'programme-guide', 'final', '2026-07-15', 'Placeholder guide attached to the Semester Exchange programme.', 'sample');

insert into public.documents (code, title, document_type, status, revised_on, description, data_source)
values ('doc-006', 'Academic visits brochure (sample)', 'brochure', 'under-review', '2026-09-05', null, 'sample');

insert into public.documents (code, title, document_type, status, revised_on, description, data_source)
values ('doc-007', 'Outbound mobility policy (sample)', 'policy', 'draft', '2026-06-30', 'Placeholder policy document with no institution link.', 'sample');

insert into public.documents (code, title, document_type, status, revised_on, description, data_source)
values ('doc-008', 'Annual collaboration summary (sample)', 'report', 'archived', '2025-06-30', null, 'sample');

insert into public.documents (code, title, document_type, status, revised_on, description, data_source)
values ('doc-009', 'Dual degree proposal — review notes (sample)', 'other', 'under-review', '2026-09-18', null, 'sample');

insert into public.document_links (code, document_id, institution_id, agreement_id, program_id, availability_id)
values ('dl-001', (select id from public.documents where code = 'doc-001'), null, (select id from public.agreements where code = 'agr-001'), null, null);

insert into public.document_links (code, document_id, institution_id, agreement_id, program_id, availability_id)
values ('dl-002', (select id from public.documents where code = 'doc-001'), (select id from public.institutions where slug = 'smp-harbour'), null, null, null);

insert into public.document_links (code, document_id, institution_id, agreement_id, program_id, availability_id)
values ('dl-003', (select id from public.documents where code = 'doc-002'), null, (select id from public.agreements where code = 'agr-001'), null, null);

insert into public.document_links (code, document_id, institution_id, agreement_id, program_id, availability_id)
values ('dl-004', (select id from public.documents where code = 'doc-003'), null, (select id from public.agreements where code = 'agr-003'), null, null);

insert into public.document_links (code, document_id, institution_id, agreement_id, program_id, availability_id)
values ('dl-005', (select id from public.documents where code = 'doc-004'), null, (select id from public.agreements where code = 'agr-006'), null, null);

insert into public.document_links (code, document_id, institution_id, agreement_id, program_id, availability_id)
values ('dl-006', (select id from public.documents where code = 'doc-005'), null, null, (select id from public.programs where slug = 'semester-exchange'), null);

insert into public.document_links (code, document_id, institution_id, agreement_id, program_id, availability_id)
values ('dl-007', (select id from public.documents where code = 'doc-005'), null, null, null, (select id from public.program_availability where code = 'off-001'));

insert into public.document_links (code, document_id, institution_id, agreement_id, program_id, availability_id)
values ('dl-008', (select id from public.documents where code = 'doc-006'), null, null, (select id from public.programs where slug = 'academic-visits'), null);

insert into public.document_links (code, document_id, institution_id, agreement_id, program_id, availability_id)
values ('dl-009', (select id from public.documents where code = 'doc-009'), null, (select id from public.agreements where code = 'agr-007'), null, null);

insert into public.document_links (code, document_id, institution_id, agreement_id, program_id, availability_id)
values ('dl-010', (select id from public.documents where code = 'doc-009'), (select id from public.institutions where slug = 'smp-lakes'), null, null, null);

insert into public.activities (code, title, activity_type, record_status, start_date, end_date, country_id, city, institution_id, agreement_id, summary, participants, data_source)
values ('act-001', 'Inbound faculty visit (sample)', 'inbound-visit', 'confirmed', '2026-10-14', '2026-10-16', (select id from public.countries where slug = 'united-kingdom'), 'Jaipur', (select id from public.institutions where slug = 'smp-harbour'), (select id from public.agreements where code = 'agr-001'), 'Sample visit to discuss the renewal of the framework memorandum.', 'Visiting faculty group (sample)', 'sample');

insert into public.activities (code, title, activity_type, record_status, start_date, end_date, country_id, city, institution_id, agreement_id, summary, participants, data_source)
values ('act-002', 'Outbound delegation (sample)', 'delegation', 'planned', '2026-11-09', '2026-11-13', (select id from public.countries where slug = 'uae'), 'Dubai', (select id from public.institutions where slug = 'smp-gulf'), (select id from public.agreements where code = 'agr-008'), 'Sample delegation ahead of the agreement start date.', 'MUJ delegation (sample)', 'sample');

insert into public.activities (code, title, activity_type, record_status, start_date, end_date, country_id, city, institution_id, agreement_id, summary, participants, data_source)
values ('act-003', 'Virtual renewal meeting (sample)', 'virtual-meeting', 'confirmed', '2026-10-05', null, (select id from public.countries where slug = 'singapore'), null, (select id from public.institutions where slug = 'smp-straits'), (select id from public.agreements where code = 'agr-009'), 'Sample call to review the expiring framework memorandum.', null, 'sample');

insert into public.activities (code, title, activity_type, record_status, start_date, end_date, country_id, city, institution_id, agreement_id, summary, participants, data_source)
values ('act-004', 'International education week (sample event)', 'event', 'planned', '2026-11-23', '2026-11-27', (select id from public.countries where slug = 'india'), 'Jaipur', null, null, 'Sample on-campus event not tied to one institution.', 'Open to MUJ students and staff (sample)', 'sample');

insert into public.activities (code, title, activity_type, record_status, start_date, end_date, country_id, city, institution_id, agreement_id, summary, participants, data_source)
values ('act-005', 'Research partner visit (sample)', 'outbound-visit', 'completed', '2026-06-08', '2026-06-12', (select id from public.countries where slug = 'germany'), 'Munich', (select id from public.institutions where slug = 'smp-alpine'), (select id from public.agreements where code = 'agr-003'), 'Sample completed visit under the research collaboration agreement.', 'Faculty researchers (sample)', 'sample');

insert into public.activities (code, title, activity_type, record_status, start_date, end_date, country_id, city, institution_id, agreement_id, summary, participants, data_source)
values ('act-006', 'Exchange information session (sample)', 'event', 'planned', '2026-09-10', null, (select id from public.countries where slug = 'australia'), 'Jaipur', (select id from public.institutions where slug = 'smp-coastal'), null, 'Sample session whose outcome has not been recorded yet.', null, 'sample');

insert into public.activities (code, title, activity_type, record_status, start_date, end_date, country_id, city, institution_id, agreement_id, summary, participants, data_source)
values ('act-007', 'Inbound delegation (sample)', 'delegation', 'completed', '2026-04-20', '2026-04-21', (select id from public.countries where slug = 'canada'), 'Jaipur', (select id from public.institutions where slug = 'smp-lakes'), null, 'Sample delegation that led to the dual degree proposal.', 'Partner academic leadership (sample)', 'sample');

insert into public.activities (code, title, activity_type, record_status, start_date, end_date, country_id, city, institution_id, agreement_id, summary, participants, data_source)
values ('act-008', 'Partner fair visit (sample)', 'outbound-visit', 'cancelled', '2026-08-03', '2026-08-05', (select id from public.countries where slug = 'japan'), 'Tokyo', null, null, 'Sample cancelled trip with no institution recorded.', null, 'sample');

-- Seed inserts are not user activity; start local development with an empty audit log.

truncate public.audit_logs restart identity;
