/**
 * Writes supabase/seeds/*.sql from the TypeScript seed modules, so the local
 * Supabase database and the static data source hold the same records.
 *
 *   npm run db:seed:generate
 *
 * Output (local development only; never pushed to a hosted project):
 *   01_reference.sql  regions, countries, programme catalogue (public site data)
 *   02_directory.sql  institutions from the public illustrative directory
 *   03_sample.sql     FICTIONAL sample institutions, agreements, offerings,
 *                     opportunities, documents, and activities
 */

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { hub, partners } from "@/lib/data";
import { directoryRegions, institutionSlug } from "@/lib/directory";
import { activitySeed } from "@/lib/internal/data/seed/activities";
import { agreementSeed } from "@/lib/internal/data/seed/agreements";
import { documentLinkSeed, documentSeed } from "@/lib/internal/data/seed/documents";
import { institutionSeed } from "@/lib/internal/data/seed/institutions";
import { opportunitySeed } from "@/lib/internal/data/seed/opportunities";
import { availabilitySeed, programSeed } from "@/lib/internal/data/seed/programs";

type SqlValue = string | number | boolean | null | undefined;

function lit(value: SqlValue): string {
  if (value === null || value === undefined) return "null";
  if (typeof value === "number") return String(value);
  if (typeof value === "boolean") return value ? "true" : "false";
  return `'${value.replace(/'/g, "''")}'`;
}

function ref(table: string, column: string, key: string | null | undefined) {
  return key ? `(select id from public.${table} where ${column} = ${lit(key)})` : "null";
}

function insert(table: string, row: Record<string, string>) {
  const columns = Object.keys(row);
  return `insert into public.${table} (${columns.join(", ")})\nvalues (${columns
    .map((column) => row[column])
    .join(", ")});`;
}

function header(title: string, notes: string[]) {
  return [
    `-- ${title}`,
    "-- GENERATED by scripts/generate-seed-sql.ts from the TypeScript seed modules.",
    "-- Do not edit by hand; run `npm run db:seed:generate` instead.",
    "-- LOCAL DEVELOPMENT ONLY. Loaded by `supabase db reset`; never pushed to a",
    "-- hosted project (do not use `supabase db push --include-seed`).",
    ...notes.map((note) => `-- ${note}`),
    "",
  ].join("\n");
}

const regionSlug = (name: string) => institutionSlug(name);

const countrySlugByName = new Map<string, string>([
  ...partners.map((partner) => [partner.country, partner.id] as const),
  [hub.country, institutionSlug(hub.country)],
]);

function countrySlug(name: string) {
  const slug = countrySlugByName.get(name);
  if (!slug) throw new Error(`No country row for activity country "${name}"`);
  return slug;
}

// ---------------------------------------------------------------------------
// 01 reference
// ---------------------------------------------------------------------------

const reference: string[] = [
  header("Reference data derived from the public site (src/lib/data.ts).", [
    "Regions and countries come from the illustrative partner directory. The",
    "country hub city/coordinates are the single globe pin for the country, not",
    "a campus location. India (the home country) is included for activities.",
  ]),
];

directoryRegions.forEach((name, index) => {
  reference.push(
    insert("regions", {
      slug: lit(regionSlug(name)),
      name: lit(name),
      sort_order: lit(index),
      data_source: lit("directory"),
    }),
  );
});

for (const partner of partners) {
  reference.push(
    insert("countries", {
      slug: lit(partner.id),
      name: lit(partner.country),
      region_id: ref("regions", "slug", regionSlug(partner.region)),
      hub_city: lit(partner.city),
      hub_latitude: lit(partner.lat),
      hub_longitude: lit(partner.lon),
      summary: lit(partner.summary),
      is_public: lit(true),
      data_source: lit("directory"),
    }),
  );
}

reference.push(
  insert("countries", {
    slug: lit(countrySlug(hub.country)),
    name: lit(hub.country),
    region_id: "null",
    hub_city: lit(hub.city),
    hub_latitude: lit(hub.lat),
    hub_longitude: lit(hub.lon),
    summary: "null",
    is_public: lit(false),
    data_source: lit("directory"),
  }),
);

programSeed.forEach((program, index) => {
  reference.push(
    insert("programs", {
      slug: lit(program.id),
      program_type: lit(program.type),
      name: lit(program.name),
      description: lit(program.description),
      general_audience: lit(program.generalAudience),
      is_published: lit(true),
      sort_order: lit(index),
      data_source: lit(program.source),
    }),
  );
});

// ---------------------------------------------------------------------------
// 02 directory
// ---------------------------------------------------------------------------

const directory: string[] = [
  header("Institutions from the public illustrative directory (src/lib/directory.ts).", [
    "Names are sample institutions, not confirmed partners. City and coordinates",
    "are left NULL: the directory only carries the country hub city, which is",
    "not the campus city. The country-level note lives on public.countries.",
  ]),
];

for (const institution of institutionSeed.filter((row) => row.source === "directory")) {
  directory.push(
    insert("institutions", {
      slug: lit(institution.id),
      name: lit(institution.name),
      country_id: ref("countries", "slug", institution.countryId),
      city: "null",
      latitude: "null",
      longitude: "null",
      location_verified: lit(false),
      is_public: lit(true),
      data_source: lit("directory"),
    }),
  );
}

// ---------------------------------------------------------------------------
// 03 sample
// ---------------------------------------------------------------------------

const sample: string[] = [
  header("FICTIONAL SAMPLE DATA for the internal portal workflow.", [
    "Every row is marked data_source = 'sample'. None of these is a DoIC record,",
    "an agreement of Manipal University Jaipur, or a published deadline.",
    "Sample rows are never public (is_public / is_published = false).",
  ]),
];

for (const institution of institutionSeed.filter((row) => row.source === "sample")) {
  sample.push(
    insert("institutions", {
      slug: lit(institution.id),
      name: lit(institution.name),
      country_id: ref("countries", "slug", institution.countryId),
      city: "null",
      latitude: lit(institution.latitude),
      longitude: lit(institution.longitude),
      website: lit(institution.website),
      note: lit(institution.note),
      is_public: lit(false),
      data_source: lit("sample"),
    }),
  );
}

const areaNames = [...new Set(agreementSeed.flatMap((agreement) => agreement.collaborationAreas))];
for (const name of areaNames) {
  sample.push(
    insert("collaboration_areas", {
      slug: lit(institutionSlug(name)),
      name: lit(name),
      data_source: lit("sample"),
    }),
  );
}

for (const agreement of agreementSeed) {
  sample.push(
    insert("agreements", {
      code: lit(agreement.id),
      reference: lit(agreement.reference),
      institution_id: ref("institutions", "slug", agreement.institutionId),
      title: lit(agreement.title),
      agreement_type: lit(agreement.type),
      record_status: lit(agreement.recordStatus),
      start_date: lit(agreement.startDate),
      end_date: lit(agreement.endDate),
      renewal: lit(agreement.renewal),
      notes: lit(agreement.notes),
      data_source: lit(agreement.source),
    }),
  );
  agreement.collaborationAreas.forEach((name, position) => {
    sample.push(
      insert("agreement_collaboration_areas", {
        agreement_id: ref("agreements", "code", agreement.id),
        collaboration_area_id: ref("collaboration_areas", "slug", institutionSlug(name)),
        position: lit(position),
      }),
    );
  });
}

for (const offering of availabilitySeed) {
  sample.push(
    insert("program_availability", {
      code: lit(offering.id),
      program_id: ref("programs", "slug", offering.programId),
      institution_id: ref("institutions", "slug", offering.institutionId),
      agreement_id: ref("agreements", "code", offering.agreementId),
      availability: lit(offering.availability),
      duration: lit(offering.duration),
      intake: lit(offering.intake),
      application_start: lit(offering.applicationStart),
      application_end: lit(offering.applicationEnd),
      eligibility: lit(offering.eligibility),
      credit_information: lit(offering.creditInformation),
      notes: lit(offering.notes),
      is_published: lit(false),
      data_source: lit(offering.source),
    }),
  );
}

for (const opportunity of opportunitySeed) {
  sample.push(
    insert("opportunities", {
      code: lit(opportunity.id),
      title: lit(opportunity.title),
      program_id: ref("programs", "slug", opportunity.programId),
      availability_id: ref("program_availability", "code", opportunity.availabilityId),
      institution_id: ref("institutions", "slug", opportunity.institutionId),
      opens_on: lit(opportunity.opensOn),
      deadline: lit(opportunity.deadline),
      record_status: lit(opportunity.recordStatus),
      summary: lit(opportunity.summary),
      data_source: lit(opportunity.source),
    }),
  );
}

for (const document of documentSeed) {
  sample.push(
    insert("documents", {
      code: lit(document.id),
      title: lit(document.title),
      document_type: lit(document.type),
      status: lit(document.status),
      revised_on: lit(document.updatedOn),
      description: lit(document.description),
      data_source: lit(document.source),
    }),
  );
}

for (const link of documentLinkSeed) {
  sample.push(
    insert("document_links", {
      code: lit(link.id),
      document_id: ref("documents", "code", link.documentId),
      institution_id: ref("institutions", "slug", link.institutionId),
      agreement_id: ref("agreements", "code", link.agreementId),
      program_id: ref("programs", "slug", link.programId),
      availability_id: ref("program_availability", "code", link.availabilityId),
    }),
  );
}

for (const activity of activitySeed) {
  sample.push(
    insert("activities", {
      code: lit(activity.id),
      title: lit(activity.title),
      activity_type: lit(activity.type),
      record_status: lit(activity.recordStatus),
      start_date: lit(activity.startDate),
      end_date: lit(activity.endDate),
      country_id: ref("countries", "slug", countrySlug(activity.country)),
      city: lit(activity.city),
      institution_id: ref("institutions", "slug", activity.institutionId),
      agreement_id: ref("agreements", "code", activity.agreementId),
      summary: lit(activity.summary),
      participants: lit(activity.participants),
      data_source: lit(activity.source),
    }),
  );
}

sample.push(
  "-- Seed inserts are not user activity; start local development with an empty audit log.",
  "truncate public.audit_logs restart identity;",
);

const outDir = join(process.cwd(), "supabase", "seeds");
const files: [string, string[]][] = [
  ["01_reference.sql", reference],
  ["02_directory.sql", directory],
  ["03_sample.sql", sample],
];
for (const [name, statements] of files) {
  writeFileSync(join(outDir, name), `${statements.join("\n\n")}\n`);
  console.log(`wrote supabase/seeds/${name} (${statements.length - 1} statements)`);
}
