/**
 * Writes SQL from the TypeScript data modules, so Supabase and the static data
 * source hold the same records.
 *
 *   npm run db:seed:generate
 *
 * Output:
 *   supabase/seeds/01_official.sql   official MUJ data (src/lib/official): regions,
 *                                    countries, programmes, institutions, agreement
 *                                    rows, offerings, calls, documents, activities.
 *                                    Idempotent upserts; safe to load into hosted.
 *   supabase/seeds/02_directory.sql  earlier directory names kept for review
 *                                    (not public). Idempotent; safe for hosted.
 *   supabase/seeds/03_sample.sql     FICTIONAL sample rows. LOCAL DEVELOPMENT ONLY.
 *   supabase/private/muj-nodal-contacts.sql
 *                                    internal-only nodal officer contacts, from the
 *                                    gitignored data/private/muj-nodal-contacts.json.
 *                                    Gitignored; skipped when the JSON is absent.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { activitySeed } from "@/lib/internal/data/seed/activities";
import { agreementSeed } from "@/lib/internal/data/seed/agreements";
import { documentLinkSeed, documentSeed } from "@/lib/internal/data/seed/documents";
import {
  legacyDirectoryInstitutions,
  sampleInstitutions,
} from "@/lib/internal/data/seed/institutions";
import { opportunitySeed } from "@/lib/internal/data/seed/opportunities";
import { availabilitySeed } from "@/lib/internal/data/seed/programs";
import type {
  Activity,
  Agreement,
  DocumentLink,
  DocumentRecord,
  Institution,
  Opportunity,
  ProgramAvailability,
  Provenance,
} from "@/lib/internal/types";
import { officialCountries, officialRegions, referenceCountries } from "@/lib/official/countries";
import {
  officialActivities,
  officialAvailability,
  officialDocumentLinks,
  officialDocuments,
  officialOpportunities,
  officialPrograms,
} from "@/lib/official/internationalization";
import { officialAgreementRows } from "@/lib/official/partners";
import { officialAgreementRecords, officialInstitutionRecords } from "@/lib/official/records";
import { officialSources, SOURCE_REVIEWED_ON } from "@/lib/official/source";

type SqlValue = string | number | boolean | null | undefined;

function lit(value: SqlValue): string {
  if (value === null || value === undefined) return "null";
  if (typeof value === "number") return String(value);
  if (typeof value === "boolean") return value ? "true" : "false";
  return `'${value.replace(/'/g, "''")}'`;
}

function slugify(value: string) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function ref(table: string, column: string, key: string | null | undefined) {
  return key ? `(select id from public.${table} where ${column} = ${lit(key)})` : "null";
}

type Row = Record<string, string>;

function insert(table: string, row: Row) {
  const columns = Object.keys(row);
  return `insert into public.${table} (${columns.join(", ")})\nvalues (${columns
    .map((column) => row[column])
    .join(", ")});`;
}

/** Insert-or-update on a unique key, so the file can be loaded repeatedly. */
function upsert(table: string, conflict: string, row: Row) {
  const columns = Object.keys(row);
  const updates = columns
    .filter((column) => column !== conflict)
    .map((column) => `  ${column} = excluded.${column}`);
  return `${insert(table, row).slice(0, -1)}\non conflict (${conflict}) do update set\n${updates.join(",\n")};`;
}

function provenance(record: Provenance): Row {
  return {
    source_url: lit(record.sourceUrl),
    source_title: lit(record.sourceTitle),
    source_checked_on: lit(record.sourceCheckedOn),
    verification: lit(record.verification),
  };
}

function header(title: string, notes: string[]) {
  return [
    `-- ${title}`,
    "-- GENERATED by scripts/generate-seed-sql.ts. Do not edit by hand;",
    "-- run `npm run db:seed:generate` instead.",
    ...notes.map((note) => `-- ${note}`),
    "",
  ].join("\n");
}

const allCountries = [...officialCountries, ...referenceCountries];
const countrySlugByName = new Map(allCountries.map((country) => [country.name, country.id]));

function countrySlug(name: string) {
  const slug = countrySlugByName.get(name);
  if (!slug) throw new Error(`No country row for "${name}"`);
  return slug;
}

// ---------------------------------------------------------------------------
// Row builders shared by official, directory, and sample output
// ---------------------------------------------------------------------------

function institutionRow(institution: Institution): Row {
  return {
    slug: lit(institution.id),
    name: lit(institution.name),
    normalized_name: lit(institution.normalizedName),
    country_id: ref("countries", "slug", institution.countryId),
    city: lit(institution.city),
    latitude: lit(institution.latitude),
    longitude: lit(institution.longitude),
    location_verified: lit(false),
    website: lit(institution.website),
    note: lit(institution.note),
    is_public: lit(institution.isPublic && institution.source === "official"),
    data_source: lit(institution.source),
    ...provenance(institution),
  };
}

const sourceRowById = new Map(officialAgreementRows.map((row) => [row.id, row.sourceRow]));

function agreementRow(agreement: Agreement): Row {
  return {
    code: lit(agreement.id),
    reference: lit(agreement.reference),
    institution_id: ref("institutions", "slug", agreement.institutionId),
    title: lit(agreement.title),
    agreement_type: lit(agreement.type),
    type_label: lit(agreement.typeLabel),
    record_status: lit(agreement.recordStatus),
    start_date: lit(agreement.startDate),
    end_date: lit(agreement.endDate),
    renewal: lit(agreement.renewal),
    notes: lit(agreement.notes),
    source_section: lit(agreement.sourceSection),
    source_row: lit(sourceRowById.get(agreement.id)),
    is_public_summary: lit(agreement.source === "official"),
    data_source: lit(agreement.source),
    ...provenance(agreement),
  };
}

function availabilityRow(offering: ProgramAvailability): Row {
  return {
    code: lit(offering.id),
    program_id: ref("programs", "program_type", offering.programId),
    institution_id: ref("institutions", "slug", offering.institutionId),
    agreement_id: ref("agreements", "code", offering.agreementId),
    availability: lit(offering.availability),
    duration: lit(offering.duration),
    intake: lit(offering.intake),
    application_start: lit(offering.applicationStart),
    application_end: lit(offering.applicationEnd),
    eligibility: lit(offering.eligibility),
    credit_information: lit(offering.creditInformation),
    notes: lit(offering.notes),
    is_published: lit(offering.source === "official"),
    data_source: lit(offering.source),
    ...provenance(offering),
  };
}

function opportunityRow(opportunity: Opportunity): Row {
  return {
    code: lit(opportunity.id),
    title: lit(opportunity.title),
    program_id: ref("programs", "program_type", opportunity.programId),
    availability_id: ref("program_availability", "code", opportunity.availabilityId),
    institution_id: ref("institutions", "slug", opportunity.institutionId),
    opens_on: lit(opportunity.opensOn),
    deadline: lit(opportunity.deadline),
    record_status: lit(opportunity.recordStatus),
    summary: lit(opportunity.summary),
    data_source: lit(opportunity.source),
    ...provenance(opportunity),
  };
}

function documentRow(document: DocumentRecord): Row {
  return {
    code: lit(document.id),
    title: lit(document.title),
    document_type: lit(document.type),
    status: lit(document.status),
    revised_on: lit(document.updatedOn),
    description: lit(document.description),
    external_url: lit(document.url),
    publicly_accessible: lit(document.publiclyAccessible),
    data_source: lit(document.source),
    ...provenance(document),
  };
}

function documentLinkRow(link: DocumentLink): Row {
  return {
    code: lit(link.id),
    document_id: ref("documents", "code", link.documentId),
    institution_id: ref("institutions", "slug", link.institutionId),
    agreement_id: ref("agreements", "code", link.agreementId),
    program_id: ref("programs", "program_type", link.programId),
    availability_id: ref("program_availability", "code", link.availabilityId),
  };
}

function activityRow(activity: Activity): Row {
  return {
    code: lit(activity.id),
    title: lit(activity.title),
    activity_type: lit(activity.type),
    record_status: lit(activity.recordStatus),
    start_date: lit(activity.startDate),
    end_date: lit(activity.endDate),
    country_id: ref("countries", "slug", countrySlug(activity.country)),
    city: lit(activity.city),
    institution_id: ref("institutions", "slug", activity.institutionId),
    agreement_id: ref("agreements", "code", activity.agreementId),
    summary: lit(activity.summary),
    participants: lit(activity.participants),
    data_source: lit(activity.source),
    ...provenance(activity),
  };
}

// ---------------------------------------------------------------------------
// 01 official
// ---------------------------------------------------------------------------

const official: string[] = [
  header("Official MUJ Internationalization data (src/lib/official).", [
    `Source pages reviewed ${SOURCE_REVIEWED_ON}; see docs/muj-internationalization-source-audit.md.`,
    "Idempotent (insert … on conflict do update): safe to load into the hosted",
    "project inside a transaction. Contains no contact details.",
    "Agreement status and dates are not stated on the source, so every agreement",
    "row is record_status 'not-stated' with NULL dates.",
  ]),
];

officialRegions.forEach((name, index) => {
  official.push(
    upsert("regions", "slug", {
      slug: lit(slugify(name)),
      name: lit(name),
      sort_order: lit(index),
      data_source: lit("official"),
    }),
  );
});

for (const country of officialCountries) {
  official.push(
    upsert("countries", "slug", {
      slug: lit(country.id),
      name: lit(country.name),
      region_id: ref("regions", "slug", slugify(country.region)),
      hub_city: "null",
      hub_latitude: lit(country.lat),
      hub_longitude: lit(country.lon),
      summary: "null",
      is_public: lit(true),
      data_source: lit("official"),
    }),
  );
}

for (const country of referenceCountries) {
  official.push(
    upsert("countries", "slug", {
      slug: lit(country.id),
      name: lit(country.name),
      region_id: country.region ? ref("regions", "slug", slugify(country.region)) : "null",
      hub_city: "null",
      hub_latitude: lit(country.lat),
      hub_longitude: lit(country.lon),
      summary: "null",
      is_public: lit(false),
      data_source: lit("official"),
    }),
  );
}

officialPrograms.forEach((program, index) => {
  official.push(
    upsert("programs", "program_type", {
      slug: lit(program.id),
      program_type: lit(program.type),
      name: lit(program.name),
      description: lit(program.description),
      general_audience: lit(program.generalAudience),
      is_published: lit(true),
      sort_order: lit(index),
      data_source: lit(program.source),
      ...provenance(program),
    }),
  );
});

for (const institution of officialInstitutionRecords) {
  official.push(upsert("institutions", "slug", institutionRow(institution)));
}
for (const agreement of officialAgreementRecords) {
  official.push(upsert("agreements", "code", agreementRow(agreement)));
}
for (const offering of officialAvailability) {
  official.push(upsert("program_availability", "code", availabilityRow(offering)));
}
for (const opportunity of officialOpportunities) {
  official.push(upsert("opportunities", "code", opportunityRow(opportunity)));
}
for (const document of officialDocuments) {
  official.push(upsert("documents", "code", documentRow(document)));
}
for (const link of officialDocumentLinks) {
  official.push(upsert("document_links", "code", documentLinkRow(link)));
}
for (const activity of officialActivities) {
  official.push(upsert("activities", "code", activityRow(activity)));
}

// ---------------------------------------------------------------------------
// 02 directory
// ---------------------------------------------------------------------------

const directory: string[] = [
  header("Names from the earlier illustrative directory, kept for DoIC review.", [
    "None appears on the official MUJ partner page (reviewed 2026-09-30).",
    "Never public (is_public = false), verification 'needs-review', no agreements.",
    "Idempotent; requires 01_official.sql (countries) first.",
  ]),
];

for (const institution of legacyDirectoryInstitutions) {
  directory.push(upsert("institutions", "slug", institutionRow(institution)));
}

// ---------------------------------------------------------------------------
// 03 sample
// ---------------------------------------------------------------------------

const sample: string[] = [
  header("FICTIONAL SAMPLE DATA for the internal portal workflow.", [
    "LOCAL DEVELOPMENT ONLY. Loaded by `supabase db reset`; never load into a",
    "hosted project (do not use `supabase db push --include-seed`).",
    "Every row is data_source = 'sample' and never public.",
  ]),
];

for (const institution of sampleInstitutions) {
  sample.push(insert("institutions", institutionRow(institution)));
}

const areaNames = [...new Set(agreementSeed.flatMap((agreement) => agreement.collaborationAreas))];
for (const name of areaNames) {
  sample.push(
    insert("collaboration_areas", {
      slug: lit(slugify(name)),
      name: lit(name),
      data_source: lit("sample"),
    }),
  );
}

for (const agreement of agreementSeed) {
  sample.push(insert("agreements", agreementRow(agreement)));
  agreement.collaborationAreas.forEach((name, position) => {
    sample.push(
      insert("agreement_collaboration_areas", {
        agreement_id: ref("agreements", "code", agreement.id),
        collaboration_area_id: ref("collaboration_areas", "slug", slugify(name)),
        position: lit(position),
      }),
    );
  });
}
for (const offering of availabilitySeed) sample.push(insert("program_availability", availabilityRow(offering)));
for (const opportunity of opportunitySeed) sample.push(insert("opportunities", opportunityRow(opportunity)));
for (const document of documentSeed) sample.push(insert("documents", documentRow(document)));
for (const link of documentLinkSeed) sample.push(insert("document_links", documentLinkRow(link)));
for (const activity of activitySeed) sample.push(insert("activities", activityRow(activity)));

sample.push(
  "-- Seed inserts are not user activity; start local development with an empty audit log.",
  "truncate public.audit_logs restart identity;",
);

// ---------------------------------------------------------------------------
// Private: nodal officer contacts (internal-only, gitignored)
// ---------------------------------------------------------------------------

type PrivateContacts = {
  sourceUrl: string;
  checkedOn: string;
  contacts: {
    agreementId: string;
    roleLabel: string;
    name: string | null;
    phone: string | null;
    email: string | null;
  }[];
};

const root = process.cwd();
const contactsJson = join(root, "data", "private", "muj-nodal-contacts.json");
let contacts: string[] | null = null;

if (existsSync(contactsJson)) {
  const input = JSON.parse(readFileSync(contactsJson, "utf8")) as PrivateContacts;
  const institutionByAgreement = new Map(
    officialAgreementRecords.map((agreement) => [agreement.id, agreement.institutionId]),
  );
  contacts = [
    header("INTERNAL-ONLY nodal officer contacts. NEVER COMMIT THIS FILE.", [
      "From the official partner page; stored in public.institution_contacts",
      "with visibility 'internal' (readable by internal roles only).",
      "Requires 01_official.sql first. Idempotent.",
    ]),
  ];
  for (const contact of input.contacts) {
    const institutionId = institutionByAgreement.get(contact.agreementId);
    if (!institutionId) throw new Error(`Contact for unknown agreement ${contact.agreementId}`);
    if (!contact.name && !contact.phone && !contact.email) continue;
    contacts.push(
      upsert("institution_contacts", "code", {
        code: lit(`nc-${contact.agreementId}`),
        institution_id: ref("institutions", "slug", institutionId),
        agreement_id: ref("agreements", "code", contact.agreementId),
        role_label: lit(contact.roleLabel),
        full_name: lit(contact.name),
        phone: lit(contact.phone),
        email: lit(contact.email),
        visibility: lit("internal"),
        data_source: lit("official"),
        source_url: lit(input.sourceUrl),
        source_title: lit(officialSources.partners.title),
        source_checked_on: lit(input.checkedOn),
        verification: lit("source-imported"),
      }),
    );
  }
}

// ---------------------------------------------------------------------------
// Write
// ---------------------------------------------------------------------------

function write(relative: string, statements: string[]) {
  const path = join(root, relative);
  mkdirSync(join(path, ".."), { recursive: true });
  writeFileSync(path, `${statements.join("\n\n")}\n`);
  console.log(`wrote ${relative} (${statements.length - 1} statements)`);
}

write("supabase/seeds/01_official.sql", official);
write("supabase/seeds/02_directory.sql", directory);
write("supabase/seeds/03_sample.sql", sample);
if (contacts) {
  write("supabase/private/muj-nodal-contacts.sql", contacts);
} else {
  console.log("skipped supabase/private/muj-nodal-contacts.sql (data/private/muj-nodal-contacts.json not found)");
}
